server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8088
  #连接超时时间
  connection-timeout: 5000ms
  servlet:
    #映射项目路径
    context-path: /
spring:
  profiles:
    #环境
    #dev 开发
    active: dev
  jackson:
    serialization:
      #jackson返回时间戳
      write-dates-as-timestamps: true
  servlet:
    multipart:
      #文件上传大小
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    #resultful风格，找不到页面时，正常抛出错误不跳转页面
    throw-exception-if-no-handler-found: true
    #仅映射static资源文件
    static-path-pattern: /static/**
    #resultful风格，不为资源文件建立映射
  resources:
    add-mappings: false
  rabbitmq:
    listener:
      simple:
        acknowledge-mode: manual

#mybatis
mybatis-plus:
  #mapper文件
  mapper-locations: classpath:mapper/**/*.xml
  #实体扫描
  type-aliases-package: com.example.blog.entity.*
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty

  #mybatis原生配置
  configuration:
    #驼峰下划线转换
    map-underscore-to-camel-case: true
    #不开启二级缓存
    cache-enabled: false

